name: Deployment to Staging

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: [self-hosted, macOS]
    environment: staging
    steps:
      - name: deploy
        run: |
         echo "hello from the staging environment!"
      - name: webserver
        run: |
           python3 -m http.server 8080
      
